### ISSUE TITLE
Change the directory structure of category

### ISSUE THREAD

**Issue by KenyaMasuko** [yamada-ui/yamada-components#11]
### Subject

ディレクトリ構造

### Description

カテゴリページのパスを`/category/category-name/`の構造に修正して、pageの生成はコンポーネントのディレクトリ構造から読み取って自動で生成

### Are you willing to participate in the development of this feature and create a pull request?

yes

**Comment by illionillion** [comment]
@KenyaMasuko 
カテゴリのページは`/component/category-name/`で表示するようなので、 #10 と作業するコードが被るので一旦中止します。

**Comment by illionillion** [comment]
@KenyaMasuko 
#10 の変更がマージされたのでもう`dev`からブランチ切って作業してもらって大丈夫です！
