### ISSUE TITLE
Add `Dialogs` examples

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#152]
### Subject

Modals

### Description

Add [Dialogs](https://tailwindui.com/components/application-ui/overlays/dialogs).

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by taroj1205** [comment]
You may also refer to https://tailwindui.com/components/application-ui/overlays/dialogs when making these examples.

**Comment by Haru-0001** [comment]
Can I try this issues?
