### ISSUE TITLE
Add `Breadcrumbs` examples

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#194]
### Subject

`Breadcrumbs`

### Description

We need to make `Breadcrumbs` examples. You may refer to https://tailwindui.com/components/application-ui/navigation/breadcrumbs when making these examples.

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by yasmro** [comment]
May I work on this?

**Comment by taroj1205** [comment]
Of course! Thank you! Please work on it!

Good luck! I'll assign it to you now :)

**Comment by illionillion** [comment]
This issue was closed.
