### ISSUE TITLE
Add `Avatars` examples

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#198]
### Subject

`Avatars`

### Description

We need to make `Avatars` examples. You may also refer to https://tailwindui.com/components/application-ui/elements/avatars when making these examples.

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by taku10101** [comment]
I wont to try

**Comment by taroj1205** [comment]
@taku10101 Thanks for commenting!

Yes, please work on it! I will assign it to you now :)

Good luck!
