### ISSUE TITLE
Fixing Icon imports in `navbars`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#280]
### Provide the exact quote of the error or issue

Modify the part that imports icons from @yamada-ui/lucide as needed for this review.

https://github.com/yamada-ui/yamada-components/pull/267#discussion_r1660048318

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by illionillion** [comment]
I will try to correct the examples of the navbar.

**Comment by taroj1205** [comment]
@illionillion I think we should create separate issues for each category. What do you think?

**Comment by illionillion** [comment]
> @illionillion I think we should create separate issues for each category. What do you think?

@taroj1205 

I think that would be better.

**Comment by taroj1205** [comment]
> > @illionillion I think we should create separate issues for each category. What do you think?
> 
> @taroj1205
> 
> I think that would be better.

@illionillion Let's create these issues!
