### ISSUE TITLE
Add `Skeleton` example

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#281]
### Subject

Add `Skeleton` example

### Description

Create a `Skeleton` example with `Skeleton` components.

https://yamada-ui.com/components/feedback/skeleton

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by kaitobq** [comment]
Can I try this?

**Comment by illionillion** [comment]
> Can I try this?

Yes!!
Good Luck!!

**Comment by kaitobq** [comment]
@illionillion 
Like the components page of yamadaUI, shoud I create Change Colors, Change Size...　etc.?

**Comment by illionillion** [comment]
> @illionillion Like the components page of yamadaUI, shoud I create Change Colors, Change Size...　etc.?

I would like to see a component created that is unique, using Skeleton and nothing else, rather than copied straight from the documentation page.

For example, how about using Skeleton when loading the message list, or using Skeleton to create the state of AI during its generation?

**Comment by kaitobq** [comment]
@illionillion 
I was thinking something like this.
Can I implement loading using Skeleton, Skeleton Text, Skeleton Circle. and place a reload button?
<img width="1710" alt="スクリーンショット 2024-07-05 13 17 11" src="https://github.com/yamada-ui/yamada-components/assets/157810570/afd28e04-ff18-4457-b990-7831612b9444">
<img width="1710" alt="スクリーンショット 2024-07-05 13 17 18" src="https://github.com/yamada-ui/yamada-components/assets/157810570/219182d6-cf17-4a64-bd83-c038913a4e1a">

**Comment by illionillion** [comment]
> @illionillion I was thinking something like this. Can I implement loading using Skeleton, Skeleton Text, Skeleton Circle. and place a reload button? <img alt="スクリーンショット 2024-07-05 13 17 11" width="1710" src="https://private-user-images.githubusercontent.com/157810570/345999568-afd28e04-ff18-4457-b990-7831612b9444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzA2OTgsIm5iZiI6MTcyMDE3MDM5OCwicGF0aCI6Ii8xNTc4MTA1NzAvMzQ1OTk5NTY4LWFmZDI4ZTA0LWZmMTgtNDQ1Ny1iOTkwLTc4MzE2MTJiOTQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwOTA2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjhhZmQ4OTVlZWY1NGYyNzUwMzZkN2RmZTljMGNkZmI0MDA4MDM1NGNhYzI1ZDY4MDMxMzg5ZjRmN2ExOGY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RyaE9qxS3J6nbrErPmBJ0xUKT-GkGkALStJy1A-V5Sg"> <img alt="スクリーンショット 2024-07-05 13 17 18" width="1710" src="https://private-user-images.githubusercontent.com/157810570/345999579-219182d6-cf17-4a64-bd83-c038913a4e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzA2OTgsIm5iZiI6MTcyMDE3MDM5OCwicGF0aCI6Ii8xNTc4MTA1NzAvMzQ1OTk5NTc5LTIxOTE4MmQ2LWNmMTctNGE2NC1iZDgzLWMwMzg5MTNhNGUxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwOTA2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjY3YjIwZWVkYjVhYThiZmI5NTkxY2JlNTk0MjEzMzJmMjEyYjIzZjA5OTE2YjQ4NTYwYjE4YjU3ODJkZmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z7MDvfFyrGqtbl1MV4K58Nl_aQmZ_br805CXDZXd-Sk">

I think that's fine.
