### ISSUE TITLE
Fix icon imports in `headers`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#300]
### Provide the exact quote of the error or issue

We should modify the icon imports from `@yamada-ui/lucide` to be `{IconName}Icon`.

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by cidkumagai** [comment]
I'll try it.

**Comment by cidkumagai** [comment]
@taroj1205 
I think this issue has already been addressed.

**Comment by taroj1205** [comment]
> @taroj1205 I think this issue has already been addressed.

@cidkumagai You're right, sorry. I will close the issue now as it has already been fixed.
