### ISSUE TITLE
Fix container query in `authentication`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#311]
**Provide the exact quote of the error or issue:**

We should modify the `_container` query to use breakpoints provided by `@yamada-ui/react`.

`contents\page-sections\authentication\with-image\index.tsx`
`contents\page-sections\authentication\with-title\index.tsx`
`contents\page-sections\authentication\forgot-password\index.tsx`
`contents\page-sections\authentication\authentication-form\index.tsx`

This issue will be automatically unassigned after two weeks have passed since it was assigned. Once unassigned, it may be picked up by someone else for work.

**Comment by illionillion** [comment]
I'll try it.
