### ISSUE TITLE
Fix container query in `headers`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#312]
**Provide the exact quote of the error or issue:**

We should modify the `_container` query to use breakpoints provided by `@yamada-ui/react`.

`contents\layouts\headers\double-header\index.tsx`
`contents\layouts\headers\simple-header\index.tsx`

This issue will be automatically unassigned after two weeks have passed since it was assigned. Once unassigned, it may be picked up by someone else for work.

**Comment by illionillion** [comment]
I try it.

**Comment by illionillion** [comment]
I try it.
