### ISSUE TITLE
Fix container query in `footers`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#315]
**Provide the exact quote of the error or issue:**

We should modify the `_container` query to use breakpoints provided by `@yamada-ui/react`.

`contents\layouts\footers\footer-simple\index.tsx`
`contents\layouts\footers\footer-links\index.tsx`
`contents\layouts\footers\footer-centerd\index.tsx`
`contents\layouts\footers\footer-social-icons\index.tsx`

This issue will be automatically unassigned after two weeks have passed since it was assigned. Once unassigned, it may be picked up by someone else for work.

**Comment by quantumshiro** [comment]
I'll try this

**Comment by taroj1205** [comment]
Hi @quantumshiro, would you mind if I overtake this issue? I would like to make refactoring changes to footer examples (#401), and I will be overriding what you will be doing here.
If you still want to work on this issue, I can wait for your PR to be merged.
