### ISSUE TITLE
Missing or invalid description in `navbars`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#320]
### Provide the exact quote of the error or issue

The following are missing and need to be added in `navbars`:

- Missing Japanese description in `contents/navigation/navbars/simple-navbar/metadata.json`
- Missing English description in `contents/navigation/navbars/simple-navbar/metadata.json`

- Missing Japanese translation for description in `contents/navigation/navbars/simple-navbar/metadata.json`

#### Invalid format

Title should be `Example Title` instead of `ExampleTitle`

- Invalid format for `SimpleNavbar` in `contents/navigation/navbars/simple-navbar/metadata.json`
- Invalid format for `Navbar With SegmentedControl` in `contents/navigation/navbars/simple-navbar/metadata.json`
- Invalid format for `NavbarWithTooltips` in `contents/navigation/navbars/simple-navbar/metadata.json`

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by illionillion** [comment]
I try it.
