### ISSUE TITLE
Invalid format in `button-group`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#321]
### Provide the exact quote of the error or issue

The following are missing and need to be added in `button-group`:

#### Invalid format

Title should be `Example Title` instead of `ExampleTitle`

- Invalid format for `BasicButtonGroup` in `contents/forms/button-group/basic-button-group/metadata.json`

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by MonsieurRadiant** [comment]
fixed in pr #328
