### ISSUE TITLE
Missing or invalid description in `page-sections`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#322]
### Provide the exact quote of the error or issue

The following are missing and need to be added in `page-sections`:

- Missing Japanese description in `contents/page-sections/metadata.json`
- Missing English description in `contents/page-sections/metadata.json`

- Missing Japanese translation for description in `contents/page-sections/metadata.json`

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by fffk10** [comment]
I'll do this.
