### ISSUE TITLE
Invalid format in `buttons`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#323]
### Provide the exact quote of the error or issue

The following are missing and need to be added in `buttons`:

#### Invalid format

Title should be `Example Title` instead of `ExampleTitle`

- Invalid format for `PrimaryButton` in `contents/forms/buttons/primary-button/metadata.json`

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by MonsieurRadiant** [comment]
fixed in pull request #327
