### ISSUE TITLE
Fix icon imports in `authentication`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#324]
### Provide the exact quote of the error or issue:

We should modify the icon imports from `@yamada-ui/lucide` to be `{IconName}Icon`.

- `contents/page-sections/authentication/with-image/index.tsx`
  - `import { Eye, EyeOff } from "@yamada-ui/lucide"`
- `contents/page-sections/authentication/forgot-password/index.tsx`
  - `import { ArrowLeft } from "@yamada-ui/lucide"`
- `contents/page-sections/authentication/with-title/index.tsx`
  - `import { Eye, EyeOff } from "@yamada-ui/lucide"`

This issue will be automatically unassigned after two weeks have passed since it was assigned. Once unassigned, it may be picked up by someone else for work.

**Comment by Achal-00** [comment]
Hey, I would like to work on this.

**Comment by MonsieurRadiant** [comment]
I have fixed them in pull request #326 . Any future issue pls @ me
