### ISSUE TITLE
Fixing `Quest Progress`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#505]
### Subject

Fixing `Quest Progress` Component

### Description

- Too much white space.
- Rounded corners on progress bar to make it uniform

### Are you willing to participate in the development of this component and create a pull request?

None

**Comment by RudhraBharathy** [comment]
Hi, @illionillion I'm interested in solving this issue, also could you please give me more info about the white space.
TIA

**Comment by illionillion** [comment]
> Hi, @illionillion I'm interested in solving this issue, also could you please give me more info about the white space. TIA

Hi, @RudhraBharathy !!
I leave it to you!!
Good Luck!!
