### ISSUE TITLE
Fix layout misalignment with pagination page number digits.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#506]
### Subject

Fix layout misalignment with pagination page number digits.

### Description

Fix layout discrepancy between 1-digit, 2-digit, and 3-digit.

![image](https://github.com/user-attachments/assets/2b6020c2-3497-4f5c-b98f-7bc40330607c)
![image](https://github.com/user-attachments/assets/4f54cd48-f271-4b59-a5c1-5a56984420ef)

### Are you willing to participate in the development of this component and create a pull request?

None

**Comment by Ncode-93** [comment]
Hey @illionillion  I'm interested in solving this.

**Comment by illionillion** [comment]
> Hey @illionillion I'm interested in solving this.

Hi! @Ncode-93 
I would very much appreciate your cooperation!
I have assigned you!

**Comment by hirotomoyamada** [comment]
@Ncode-93

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.
