### ISSUE TITLE
Fix Simple pagination button

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#516]
### Subject

Fix Simple pagination button

### Description

Fix nested buttons.
![image](https://github.com/user-attachments/assets/373ab7fd-19b5-4914-97c7-ca3bf7476523)

### Are you willing to participate in the development of this component and create a pull request?

None

**Comment by RudhraBharathy** [comment]
@illionillion I can fix this issue, please assign it to me!!

**Comment by illionillion** [comment]
> @illionillion I can fix this issue, please assign it to me!!

Hi @RudhraBharathy !
I leave it to you.
Good luck!!
