### ISSUE TITLE
Replacing the same image with another image.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#526]
### Subject

Replacing the same image with another image.

### Description

The following components use the same images as Mantine and others, so replace them with different images.

- `/page-sections/authentication/with-image`
  - https://ui.mantine.dev/component/authentication-image/
- `/page-sections/faq/with-image`
  - https://ui.mantine.dev/component/faq-with-image/
- `/page-sections/hero-headers/with-background-image`
  - https://ui.mantine.dev/component/faq-with-image/
- `/page-sections/hero-headers/with-bullets`
  - https://ui.mantine.dev/component/hero-bullets/
- `/page-sections/hero-headers/with-content-on-left`
  - https://ui.mantine.dev/component/hero-content-left/

### Are you willing to participate in the development of this component and create a pull request?

None

**Comment by taroj1205** [comment]
Hey @Haru-0001, are you still working on this?

**Comment by Haru-0001** [comment]
> Hey @Haru-0001, are you still working on this?

Sorry, I was too busy to work on it. I would like to ask someone else to handle it.

**Comment by illionillion** [comment]
> Hey @taroj1205 / @illionillion,
> 
> Leave it to me!!! Additionally, is there a particular website that you guys recommend for selecting images?

Hi @RudhraBharathy 
Yes please!!

**Comment by illionillion** [comment]
> Hey @taroj1205 / @illionillion,
> 
> Leave it to me!!! Additionally, is there a particular website that you guys recommend for selecting images?

Hey @RudhraBharathy .

What about these?

https://unsplash.com/
https://pixabay.com/
https://www.pexels.com/

Any of these that are free to use and do not require a license label, etc. are fine.
