### ISSUE TITLE
Create `Navbar with search` component

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-components#527]
### Subject

Create `Navbar with search` component

### Description

Create `Navbar with search` component

https://ui.mantine.dev/component/navbar-search/

- Using Yamada UI components
- Keep text color, size, background color, and margins the same as much as possible.
- Make cool stuff.

### Are you willing to participate in the development of this component and create a pull request?

None

**Comment by nathanlao** [comment]
Hi @illionillion, may I work on this issue, please? I would love to contribute!

**Comment by illionillion** [comment]
> Hi @illionillion, may I work on this issue, please? I would love to contribute!

Hi @nathanlao.
I assigned you!
Good Luck!!
