### ISSUE TITLE
Hidden components appear in search results

### ISSUE THREAD

**Issue by Haru-0001** [yamada-ui/yamada-components#531]
### Action taken
Set `ignore:true` to options
`contents/typography/headings/full-gradient-heading/metadata.json`
and
`contents/typography/headings/partial-gradient/metadata.json`

This phenomenon is not limited to the files noted.

### Provide the exact quote of the error or issue

Components set to `ignore:true` in `metadeta.json` appear in search results.

![image](https://github.com/user-attachments/assets/09c1b332-8047-432a-b6be-8d76216a8949)
*`Partial Gradient Heading` already set to `ignore:true`

Also, even if all components under a category have ignore:true, that category will still appear in the search results and an empty category can still be accessed.

![image](https://github.com/user-attachments/assets/15f61c45-5b8c-4106-a713-2de66539a7fb)
![image](https://github.com/user-attachments/assets/0ec0ced2-6262-424c-b5d5-f8bd4f5f43b9)

P.S. I set `ignore:true` in `options` of  `contents/typography/texts/metadata.json`, but the parent category `typography` is displayed.
![image](https://github.com/user-attachments/assets/3d8f67fe-8a91-4bdc-8bcb-9c97bc61dc98)

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by taroj1205** [comment]
> Components set to ignore:true in metadeta.json appear in search results.
Hi @Haru-0001, this issue will likely be fixed when you run `pnpm gen:search`.

**Comment by Haru-0001** [comment]
> > Components set to ignore:true in metadeta.json appear in search results.
> 
> Hi @Haru-0001, this issue will likely be fixed when you run `pnpm gen:search`.

Thank you for your reply.
The following error occurred when it was run.
```
tsx scripts/search-content

┌  Generating Yamada Components search content
│
◇  Got the Yamada UI content paths
│
▲  An error occurred
└  Cannot read properties of undefined (reading 'title')
```
I have already run `git pull` and `pnpm i`.
Could there be an issue with my environment that's causing this error? 
I'd appreciate your thoughts on this.

**Comment by taroj1205** [comment]
> > > Components set to ignore:true in metadeta.json appear in search results.
> > 
> > 
> > Hi @Haru-0001, this issue will likely be fixed when you run `pnpm gen:search`.
> 
> Thank you for your reply. The following error occurred when it was run.
> 
> ```
> tsx scripts/search-content
> 
> ┌  Generating Yamada Components search content
> │
> ◇  Got the Yamada UI content paths
> │
> ▲  An error occurred
> └  Cannot read properties of undefined (reading 'title')
> ```
> 
> I have already run `git pull` and `pnpm i`. Could there be an issue with my environment that's causing this error? I'd appreciate your thoughts on this.

Seems like there is an issue in the script.
Please create an issue regarding this, and I will fix it. If you're busy atm, I am also happy to create the issue for you.

**Comment by Haru-0001** [comment]
> > > > Components set to ignore:true in metadeta.json appear in search results.
> > > 
> > > 
> > > Hi @Haru-0001, this issue will likely be fixed when you run `pnpm gen:search`.
> > 
> > 
> > Thank you for your reply. The following error occurred when it was run.
> > ```
> > tsx scripts/search-content
> > 
> > ┌  Generating Yamada Components search content
> > │
> > ◇  Got the Yamada UI content paths
> > │
> > ▲  An error occurred
> > └  Cannot read properties of undefined (reading 'title')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have already run `git pull` and `pnpm i`. Could there be an issue with my environment that's causing this error? I'd appreciate your thoughts on this.
> 
> Seems like there is an issue in the script. Please create an issue regarding this, and I will fix it. If you're busy atm, I am also happy to create the issue for you.

Thank you for your prompt reply. Understood, I’ll go ahead and create the issue.

**Comment by taroj1205** [comment]
> I set ignore:true in options of contents/typography/texts/metadata.json, but the parent category typography is displayed.

I will work on fixing this issue.
