### ISSUE TITLE
Add `Navbars`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#67]
### Subject

Navbars

### Description

Add [Navbars](https://ui.mantine.dev/category/navbars/)

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by taroj1205** [comment]
You may also refer to https://tailwindui.com/components/application-ui/navigation/navbars when making these examples.

**Comment by illionillion** [comment]
I would like to try it.

**Comment by illionillion** [comment]
Add https://tailwindui.com/components/application-ui/navigation/sidebar-navigation.

**Comment by illionillion** [comment]
Add Tailwind CSS Vertical Navigation
[Tailwind CSS Vertical Navigation](https://tailwindui.com/components/application-ui/navigation/vertical-navigation)

**Comment by illionillion** [comment]
Since the minimum components are now in place, this issue will be closed.
