### ISSUE TITLE
Add `Inputs` examples

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#74]
### Subject

Inputs

### Description

Add [Inputs](https://ui.mantine.dev/category/inputs/)

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by taroj1205** [comment]
You may also refer to https://tailwindui.com/components/application-ui/forms/input-groups when making these examples.

**Comment by okuyama-GMOPG** [comment]
I'll do it!

**Comment by yamao-latte** [comment]
I'll do it!

**Comment by illionillion** [comment]
This issue was closed.
