### ISSUE TITLE
Add `Buttons` examples

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-components#75]
### Subject

Buttons

### Description

Add [Buttons](https://ui.mantine.dev/category/buttons/)

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by taroj1205** [comment]
You may also refer to https://tailwindui.com/components/application-ui/elements/buttons when making these components.

**Comment by suzukisan22** [comment]
i'll take it!

**Comment by taroj1205** [comment]
@taku10101 Do you plan to add any more examples?

**Comment by illionillion** [comment]
This issue was closed.
